org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

mod.id=bounce_styles
mod.name=BounceStyles
mod.group=dev.bsmp
mod.version=3.1.2
mod.authors=RyanV
mod.description=
mod.website=
mod.source=
mod.issues=

deps.fabric.loader=0.19.3
deps.fabric.loom=1.17-SNAPSHOT
deps.moddev=2.0.141

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=
publish.curseforge=
#publish.additionalVersions=