org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

mod.name = BounceStyles
mod.id = bounce_styles
archives_base_name = bouncestyles
mod.group = dev.bsmp
mod.version = 3.1.0

mod.license = MIT
mod.description = Add your own data-driven Cosmetics!
mod.authors = RyanV
mod.source_url=https://github.com/BounceSMP/bouncestyles
mod.issue_tracker=https://github.com/BounceSMP/bouncestyles/issues
mod.icon=bs_icon.png
#mod.general_website=UNSET

deps.fabric-loader=0.19.2
deps.fabric-loom=1.16-SNAPSHOT
deps.moddev=2.0.141

deps.minecraft=[VERSIONED]
deps.fabric.api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=
publish.curseforge=